name: 自动打包发布程序

on:
  push:
    tags:
      - 'v*'  # 添加标签推送触发
  workflow_dispatch:
    inputs:
      version:
        description: '输入自定义版本号 (例如: 1.2.3)'
        required: false
        default: 'dev'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 缓存Nuitka构建文件
        uses: actions/cache@v3
        with:
          path: |
            ~\.cache\pip
            ~\.cache\nuitka
            build\
          key: ${{ runner.os }}-nuitka-${{ hashFiles('**/requirements.txt') }}

      # 新增Nuitka安装和打包步骤
      - name: 安装Nuitka
        run: pip install nuitka

      - name: 打包main.py
        run: nuitka --standalone --enable-plugin=tk-inter --output-dir=build main.py

      - name: 打包hira2roma.py
        run: nuitka --standalone --enable-plugin=tk-inter --output-dir=build hira2roma.py

      - name: 重命名主程序
        run: ren build\main.exe build\TextGrid2oto.exe

      - name: 创建发布压缩包
        shell: pwsh
        run: |
          # 处理版本号逻辑
          if ("${{ github.event.inputs.version }}" -ne "") {
            $version = "${{ github.event.inputs.version }}"
          } elseif ("${{ github.ref_type }}" -eq "tag") {
            $version = "${{ github.ref_name }}".Replace("v", "")
          } else {
            $version = "dev"
          }
          # 压缩文件
          Compress-Archive -Path *.md,*.txt,*.ini,*.exe -DestinationPath "TextGrid2oto-$version.zip"

      - name: 上传发布包
        uses: actions/upload-artifact@v4
        with:
          name: TextGrid2oto-${{ github.event.inputs.version || 'dev' }}
          path: TextGrid2oto-*.zip