name: 自动打包程序，并上传到Release
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 下载源码
        uses: actions/checkout@v2
      # nuitka --standalone --onefile --output-filename=TextGrid2oto_v0.1.5 main.py
      - name: 下载并安装依赖
        run: |
          pip install nuitka
          ls
