name: 自动打包发布程序

on:
  push:
    tags:
      - 'v*'  # 添加标签推送触发
  workflow_dispatch:
    inputs:
      version:
        description: '输入自定义版本号 (例如: 1.2.3)'
        required: false
        default: '0.1.2'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: 创建缓存目录
        run: |
          mkdir -p ~/.cache/pip
          mkdir -p ~/.cache/nuitka
          mkdir -p ~/.cache/build

      - name: 恢复依赖项缓存
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/nuitka
            ~/.cache/build
          key: ${{ runner.os }}-build-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: 安装Nuitka
        run: pip install nuitka

      - name: 打包main.py
        run: nuitka --standalone --onefile --enable-plugin=tk-inter --output-dir=build --assume-yes-for-downloads main.py

      - name: 打包hira2roma.py
        run: nuitka --standalone --onefile --enable-plugin=tk-inter --output-dir=build --assume-yes-for-downloads hira2roma.py

      - name: 重命名主程序并移动文件
        run: |
          Rename-Item D:\a\TextGrid2oto\TextGrid2oto\build\main.exe -NewName D:\a\TextGrid2oto\TextGrid2oto\build\TextGrid2oto.exe
          Copy-Item D:\a\TextGrid2oto\TextGrid2oto\build\TextGrid2oto.exe -Destination D:\a\TextGrid2oto\TextGrid2oto\TextGrid2oto.exe
          Copy-Item D:\a\TextGrid2oto\TextGrid2oto\build\hira2roma.exe -Destination D:\a\TextGrid2oto\TextGrid2oto\hira2roma.exe

      - name: 缓存构建输出
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/nuitka
            ~/.cache/build
          key: ${{ runner.os }}-build-output-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-output-

      - name: 创建发布压缩包
        shell: pwsh
        run: |
          # 处理版本号逻辑
          if ("${{ github.event.inputs.version }}" -ne "") {
            $version = "${{ github.event.inputs.version }}"
          } elseif ("${{ github.ref_type }}" -eq "tag") {
            $version = "${{ github.ref_name }}".Replace("v", "")
          } else {
            $version = "dev"
          }
          # 压缩文件
          Compress-Archive -Path D:\a\TextGrid2oto\TextGrid2oto\*.md,D:\a\TextGrid2oto\TextGrid2oto\*.txt,D:\a\TextGrid2oto\TextGrid2oto\*.ini,D:\a\TextGrid2oto\TextGrid2oto\*.exe -DestinationPath D:\a\TextGrid2oto\TextGrid2oto\TextGrid2oto-$version-windows.zip

      - name: 发布到 GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release $version"
          draft: false
          prerelease: false
          files: |
            TextGrid2oto-*-windows.zip
          body: |
            ## 版本 $version 更新内容

            ### 包含组件
            - TextGrid2oto (Windows x64)
            - hira2roma (Windows x64)

            ### 配置文件
            - run-config.txt
            - presamp.ini
            - opencpop-extension.txt
            - hira2roma-list.txt
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}