name: 自动打包发布程序

on:
  push:
    tags:
      - 'v*'  # 添加标签推送触发
  workflow_dispatch:
    inputs:
      version:
        description: '输入自定义版本号 (例如: 1.2.3)'
        required: false
        default: '0.1.2'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 缓存Nuitka构建文件
        uses: actions/cache@v3
        with:
          path: |
            ~\.cache\pip
            ~\.cache\nuitka
            build\
          key: ${{ runner.os }}-nuitka-${{ hashFiles('**/requirements.txt') }}

      # 新增Nuitka安装和打包步骤
      - name: 安装Nuitka
        run: pip install nuitka

      - name: 打包main.py
        run: nuitka --standalone --onefile --enable-plugin=tk-inter --output-dir=build --assume-yes-for-downloads main.py

      - name: 打包hira2roma.py
        run: nuitka --standalone --onefile --enable-plugin=tk-inter --output-dir=build --assume-yes-for-downloads hira2roma.py

      - name: 重命名主程序
        run: |
          Rename-Item -Path main.exe -NewName TextGrid2oto.exe

      - name: 创建发布压缩包
        shell: pwsh
        run: |
          # 处理版本号逻辑
          if ("${{ github.event.inputs.version }}" -ne "") {
            $version = "${{ github.event.inputs.version }}"
          } elseif ("${{ github.ref_type }}" -eq "tag") {
            $version = "${{ github.ref_name }}".Replace("v", "")
          } else {
            $version = "dev"
          }
          # 压缩文件
          Compress-Archive -Path *.md,*.txt,*.ini,*.exe -DestinationPath "TextGrid2oto-$version-windows.zip"

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
          files: |
            TextGrid2oto-*-windows.zip
          body: |
            ## 版本 ${{ github.ref_name }} 更新内容

            ### 包含组件
            - TextGrid2oto (Windows x64)
            - hira2roma (Windows x64)

            ### 配置文件
            - run-config.txt
            - presamp.ini
            - opencpop-extension.txt
            - hira2roma-list.txt