name: 自动打包发布程序

on:
  push:
    tags:
      - 'v*'  # 添加标签推送触发
  workflow_dispatch:
    inputs:
      version:
        description: '输入自定义版本号 (例如: 1.2.3)'
        required: false
        default: '0.1.2'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4


      - name: 安装Nuitka
        run: pip install nuitka

      - name: 并行打包
        run: |
          # 启动两个后台任务进行打包
          Start-Job -ScriptBlock { nuitka --standalone --onefile --enable-plugin=tk-inter --output-filename=TextGrid2oto --assume-yes-for-downloads main.py }
          Start-Job -ScriptBlock { nuitka --standalone --onefile --enable-plugin=tk-inter --assume-yes-for-downloads hira2roma.py }
          # 等待所有任务完成
          Get-Job | Wait-Job

      - name: 创建发布压缩包
        id: create_release
        shell: pwsh
        run: |
          # 获取前一个tag
          $previous_tag = git describe --tags --abbrev=0 HEAD^ 2>$null
          if (-not $previous_tag) { $previous_tag = "v0.1.0" }  # 设置默认初始版本

          # 处理版本号逻辑
          if ("${{ github.event.inputs.version }}" -ne "") {
            $version = "${{ github.event.inputs.version }}"
          } elseif ("${{ github.ref_type }}" -eq "tag") {
            $version = "${{ github.ref_name }}".Replace("v", "")
          } else {
            $version = "Test"
          }
          
          # 设置输出变量
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "previous_tag=$previous_tag" >> $env:GITHUB_OUTPUT

          body: |
            ## 版本 ${{ steps.create_release.outputs.version }} 更新内容
            https://github.com/xiaobaijunya/TextGrid2oto/compare/${{ steps.create_release.outputs.previous_tag }}...v${{ steps.create_release.outputs.version }}
            ### 变更记录
            ### 包含组件
            - TextGrid2oto (Windows x64)
            - hira2roma (Windows x64)
            ### 说明文件
            - README.md
            ### 配置文件
            - run-config.txt
            - run-config-CVVC.txt
            - run-config-VCV.txt
            - run-config-VCR.txt
            - opencpop-extension.txt
            - hira2roma-list.txt
            - jp-romaji-presamp.ini
            - presamp.ini（中文CVVC用）
            - 樗儿中文VCV-presamp.ini
            - CVR-presamp.ini（中文CV音源用）
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}