name: Auto Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: '输入自定义版本号 (例如: 1.2.3)'
        required: false
        default: 'dev'

jobs:
  build:
    name: Build ${{ matrix.app }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        app: [main, hira2roma]
        include:
          - os: windows-latest
            sys_name: windows
            arch: x64
          - app: main
            pkg_name: TextGrid2oto
          - app: hira2roma
            pkg_name: hira2roma

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Nuitka
        run: pip install nuitka

      # 在构建步骤中处理手动版本号
      - name: Build executable
        shell: bash
        run: |
          # 如果是手动触发，使用输入的版本号
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION=${GITHUB_REF_NAME#v}
          fi
          
          # 定义输出文件名模板
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            OUTPUT_FILE="${{ matrix.pkg_name }}-${VERSION}-${{ matrix.sys_name }}-${{ matrix.arch }}.exe"
          else
            OUTPUT_FILE="${{ matrix.pkg_name }}-${VERSION}-${{ matrix.sys_name }}-${{ matrix.arch }}"
          fi

          # 执行Nuitka打包（添加自动下载许可参数）
          python -m nuitka --standalone --onefile --assume-yes-for-downloads ${{ matrix.app }}.py
          
          # 重命名输出文件
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv ${{ matrix.app }}.exe "${OUTPUT_FILE}"
          else
            mv ${{ matrix.app }} "${OUTPUT_FILE}"
          fi

          # 显示生成文件信息
          ls -lh "${OUTPUT_FILE}"

      - name: Verify existing files
        run: |
          echo "工作目录内容:"
          ls -l
          echo "必需配置文件:"
          ls run-config.txt presamp.ini opencpop-extension.txt hira2roma-list.txt README.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkg_name }}-${{ matrix.sys_name }}
          path: |
            ${{ matrix.pkg_name }}-*-${{ matrix.sys_name }}*
            run-config.txt
            presamp.ini
            opencpop-extension.txt
            hira2roma-list.txt
            README.md

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir release_assets
          find artifacts -type f \( -name "*.exe" -o -name "*.txt" -o -name "*.ini" -o -name "*.md" \) -exec cp -v {} release_assets \;
          ls -lh release_assets

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: "Release ${{ github.ref_name }}"
          body: "Auto-generated build for version ${{ github.ref_name }}"
          files: |
            release_assets/*