name: Python Multi-Platform Build

on:
  push:
    paths:
      - 'main.py'
      - 'hira2roma.py'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: |
          if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
            sudo apt-get update
            sudo apt-get install -y python3-dev
          elif [[ ${{ matrix.os }} == 'macos-latest' ]]; then
            brew install python
          fi

      - name: Install Nuitka
        run: |
          python -m pip install --upgrade pip
          python -m pip install nuitka

      - name: Build executables
        run: |
          # 打包 main.py
          python -m nuitka --standalone --onefile \
            --output-filename="TextGrid2oto_${{ matrix.os }}_py${{ matrix.python-version }}" \
            --output-dir=dist/${{ matrix.os }} main.py
      
          # 打包 hira2roma.py
          python -m nuitka --standalone --onefile \
            --output-filename="hira2roma_${{ matrix.os }}_py${{ matrix.python-version }}" \
            --output-dir=dist/${{ matrix.os }} hira2roma.py

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-binaries
          path: dist/${{ matrix.os }}/
          retention-days: 30
